version: "3"

services:

################################################
  # mongodb & mongo-express
  ###############################################
  mongo.photobox:
    image: mongo:latest
    container_name: mongo_photobox
    volumes:
      - ./data:/var/data
    working_dir: /var/data
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    links:
      - mongo.photobox:mongo
